project_name: aws-resource-exporter
builds:
- env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  ignore:
  - goos: darwin
archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
checksum:
  name_template: 'aws-resource-exporter-linux-amd64.sha256'
  algorithm: sha256
release:
  name_template: "Release {{.Tag}}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
